presubmits:  
  kubernetes/test-infra:
  - name: pull-test-infra-bazel-canary
    always_run: false
    decorate: true
    labels:
      preset-service-account: "true"
      preset-bazel-scratch-dir: "true"
      preset-bazel-remote-cache-enabled: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:latest-experimental
        imagePullPolicy: Always
        command:
        - runner.sh
        - ./scenarios/kubernetes_execute_bazel.py
        args:
        - hack/build-then-unit.sh
        # Bazel needs privileged mode in order to sandbox builds.
        securityContext:
          privileged: true
        volumeMounts:
        resources:
          requests:
            memory: "2Gi"
