postsubmits:
  kubernetes/test-infra:
  - name: post-test-infra-build-smoke
    agent: knative-build
    decorate: true
    build_spec:
      steps:
      - name: first
        image: busybox
        args: ["echo", "hello"]
      - name: second
        image: busybox
        args: ["echo", "world"]
      - name: third
        image: busybox
        args: ["cat", "config/jobs/kubernetes/test-infra/test-infra-postsubmits.yaml"]

  - name: ci-test-infra-bazel
    branches:
    - master
    decorate: true
    labels:
      preset-service-account: "true"
      preset-bazel-scratch-dir: "true"
      preset-bazel-remote-cache-enabled: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20190110-49573aea5-experimental
        command:
        - runner.sh
        - ./scenarios/kubernetes_bazel.py
        args:
        - --build=//...
        - --install=gubernator/test_requirements.txt
        - --test=//...
        - --test-args=--test_output=errors
        # Bazel needs privileged mode in order to sandbox builds.
        securityContext:
          privileged: true
        resources:
          requests:
            memory: "2Gi"

  - name: maintenance-boskos-config-upload
    branches:
    - master
    decorate: true
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20190110-49573aea5-experimental
        command:
        - runner.sh
        args:
        - ./boskos/update_prow_config.sh
        env:
        - name: PROW_SERVICE_ACCOUNT
          value: /etc/prow-build-service/prow-build-service.json
        volumeMounts:
        - name: prow-build-service
          mountPath: /etc/prow-build-service
          readOnly: true
      volumes:
      - name: prow-build-service
        secret:
          secretName: prow-build-service

  - name: maintenance-ci-testgrid-config-upload
    branches:
    - master
    labels:
      preset-service-account: "true"
      preset-bazel-scratch-dir: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20190110-49573aea5-experimental
        command:
        - runner.sh
        args:
        - ./testgrid/config-upload.sh
        resources:
          requests:
            memory: "1Gi"
